### ISSUE TITLE
View UX 최적화

### ISSUE THREAD

**Issue by DevHyeonseong** [team-MonoPad/MonoPad#71]
### flow
develop 에서 branch 따서 작업후 merge
### TODO
- [x] 트레일러, 추천영화등이 없으면 해당 TextView와 Divider View.GONE 처리하기 981c952
- [x] ImageSelectActivity 이미지 클릭시 체크박스 이벤트 처리하기 b9f46bb
- [x] DetailActivity 포스터 위치 center고정 1a8c807
- [x] Room 에서 리뷰 존재 여부 확인 후 DetailActivity menu icon 바꿔주기 a6a41f5
- [x] LiveData 사용 방법 수정 062ae53
- [x] DetailActivity kotlin extension -> data binding 237f04b
